plugins {
    id 'java'
    id 'application'
}

group = 'de.muenchen.aigner'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes["Main-Class"] = "de.muenchen.aigner.sensoren.SimulatorApp"
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

application {
    mainClass = 'de.muenchen.aigner.sensoren.SimulatorApp'
}

tasks.register('runSimulator', JavaExec) {
    group = 'application'
    description = 'Startet den Multi-Sensor-Simulator'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'de.muenchen.aigner.sensoren.SimulatorApp'

    standardInput = System.in
}