version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build: ./home-sentinel
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - AUTH_REGISTRATION_KEY=MeinGeheimesPasswort
    depends_on:
      - redis

  simulator:
    build: ./sensor-simulator
    environment:
      - BACKEND_URL=http://backend:8080
      - REGISTRATION_KEY=MeinGeheimesPasswort
    depends_on:
      - backend